version: '3.8'

services:
  linkedin-agent:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/linkedin_agent.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/linkedin_agent.db')"]
      interval: 30s
      timeout: 10s
      retries: 3 